export const MAIL_SERVICE_TYPE: 'MAIL_PRIVATE' = 'MAIL_PRIVATE'
export const THREAD_SERVICE_TYPE: 'MAIL' = 'MAIL'
export const MAIL_ATTACHMENT_SERVICE_TYPE: 'ATTACHMENT_PRIVATE' =
  'ATTACHMENT_PRIVATE'
