#!/usr/bin/env node
// Generates the plain-CSS and pre-load parts of the kit from tokens.ts, so
// they can never drift from the MUI themes:
//   hub-theme.css   CSS variables per theme, for apps without MUI
//   fonts.css       @font-face rules for the bundled Inter weights
//   boot-inline.js  snippet for index.html that paints the right background
//                   before the app loads (no flash of the wrong theme)
// Run: node shared/hub-theme/build-css.mjs   (Node 22+ reads the .ts directly)

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { cssVariables, sharedThemeTokens } from './tokens.ts';

const here = dirname(fileURLToPath(import.meta.url));
const banner = '/* Generated by shared/hub-theme/build-css.mjs from tokens.ts. Do not edit by hand. */\n';

function block(selector, vars) {
  const body = Object.entries(vars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');
  return `${selector} {\n${body}\n}\n`;
}

const css = [
  banner,
  '/* Set data-ui-theme and data-theme on <html> (boot-inline.js does this).\n',
  '   Hub 2.0 is each app\'s original look: define :root[data-ui-theme=\'hub20\'] in the app. */\n\n',
  block(":root[data-ui-theme='hub30'][data-theme='dark']", cssVariables(sharedThemeTokens('hub30', 'dark'))),
  '\n',
  block(":root[data-ui-theme='hub30'][data-theme='light']", cssVariables(sharedThemeTokens('hub30', 'light'))),
  '\n',
  block(":root[data-ui-theme='black']", cssVariables(sharedThemeTokens('black', 'dark'))),
  '\n',
  block(":root[data-ui-theme='white']", cssVariables(sharedThemeTokens('white', 'light'))),
  '\n',
  ":root[data-ui-theme='hub30'] body {\n  background: var(--qp-app-gradient);\n  background-repeat: no-repeat;\n}\n",
].join('');
writeFileSync(join(here, 'hub-theme.css'), css);

const weights = { Regular: 400, Medium: 500, SemiBold: 600, Bold: 700 };
const fonts =
  banner +
  Object.entries(weights)
    .map(
      ([name, weight]) =>
        `@font-face {\n  font-family: 'Inter';\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: swap;\n  src: url('./fonts/Inter-${name}.woff2') format('woff2');\n}\n`
    )
    .join('\n');
writeFileSync(join(here, 'fonts.css'), fonts);

const boot = {
  hub30: {
    light: sharedThemeTokens('hub30', 'light').chrome.boot,
    dark: sharedThemeTokens('hub30', 'dark').chrome.boot,
  },
  black: { light: sharedThemeTokens('black', 'dark').chrome.boot, dark: sharedThemeTokens('black', 'dark').chrome.boot },
  white: { light: sharedThemeTokens('white', 'light').chrome.boot, dark: sharedThemeTokens('white', 'light').chrome.boot },
};

const snippet = `/* Generated by shared/hub-theme/build-css.mjs from tokens.ts.
   Paste inside a <script> at the top of <head> in index.html, then set
   STORAGE_KEY and HUB20 to this app's values (same key as HubThemeProvider). */
(function () {
  var STORAGE_KEY = 'REPLACE-ui-theme';
  var HUB20 = { light: '#ffffff', dark: '#121212' };
  var BOOT = ${JSON.stringify(boot)};
  var params = new URLSearchParams(location.search);
  var mode = window._qdnTheme || params.get('theme') || 'dark';
  if (mode !== 'light' && mode !== 'dark') mode = 'dark';
  var ui = 'hub30';
  try {
    var stored = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null');
    if (stored === 'hub20' || BOOT.hasOwnProperty(stored)) ui = stored;
  } catch (e) {}
  var shown = ui === 'black' ? 'dark' : ui === 'white' ? 'light' : mode;
  var bg = ui === 'hub20' ? HUB20[mode] : BOOT[ui][mode];
  var root = document.documentElement;
  root.setAttribute('data-theme', shown);
  root.setAttribute('data-ui-theme', ui);
  root.style.colorScheme = shown;
  root.style.background = bg;
  document.addEventListener('DOMContentLoaded', function () {
    document.body.style.background = bg;
  });
})();
`;
writeFileSync(join(here, 'boot-inline.js'), snippet);

console.log('hub-theme.css, fonts.css and boot-inline.js written');
